# What drives the price of a car?

![](images/kurt.jpeg)

**OVERVIEW**

In this application, you will explore a dataset from Kaggle. The original dataset contained information on 3 million used cars. The provided dataset contains information on 426K cars to ensure speed of processing.  Your goal is to understand what factors make a car more or less expensive.  As a result of your analysis, you should provide clear recommendations to your client -- a used car dealership -- as to what consumers value in a used car.

### CRISP-DM Framework

<center>
    <img src = images/crisp.png width = 50%/>
</center>


To frame the task, throughout our practical applications, we will refer back to a standard process in industry for data projects called CRISP-DM.  This process provides a framework for working through a data problem.  Your first step in this application will be to read through a brief overview of CRISP-DM [here](https://mo-pcco.s3.us-east-1.amazonaws.com/BH-PCMLAI/module_11/readings_starter.zip).  After reading the overview, answer the questions below.

### Business Understanding

From a business perspective, we are tasked with identifying key drivers for used car prices.  In the CRISP-DM overview, we are asked to convert this business framing to a data problem definition.  Using a few sentences, reframe the task as a data task with the appropriate technical vocabulary.

In [1]:
'''
Our task can be reframed as a supervised regression problem. We will attempt to predict the price of a car given its characteristics by creating 
regression models and analyzing appropriate regression metrics. This will allow us to identify which characteristics are most correlated with car price.
Our analysis will allow dealership owners to better determine pricing and inventory for their vehicles.
'''

'\nOur task can be reframed as a supervised regression problem. We will attempt to predict the price of a car given its characteristics by creating \nregression models and analyzing appropriate regression metrics. This will allow us to identify which characteristics are most correlated with car price.\nOur analysis will allow dealership owners to better determine pricing and inventory for their vehicles.\n'

### Data Understanding

After considering the business understanding, we want to get familiar with our data.  Write down some steps that you would take to get to know the dataset and identify any quality issues within.  Take time to get to know the dataset and explore what information it contains and how this could be used to inform your business understanding.

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn import linear_model
import matplotlib.pyplot as plt
import plotly.express as px
from sklearn.metrics import mean_absolute_error,mean_squared_error
from sklearn.preprocessing import StandardScaler
df=pd.read_csv('data/vehicles.csv')

In [3]:
'''Steps to understand the data
1: Skim the dataset and note features and general characteristics
2: Identify missing values for select features
3: Investigate Outliers
4: Explore independent variable relationships to price and between other independent variables
'''

'Steps to understand the data\n1: Skim the dataset and note features and general characteristics\n2: Identify missing values for select features\n3: Investigate Outliers\n4: Explore independent variable relationships to price and between other independent variables\n'

In [4]:
#Start by viewing the dataset and seeing what features it includes
df

,id,region,price,year,manufacturer,model,condition,cylinders,fuel,odometer,title_status,transmission,VIN,drive,size,type,paint_color,state
0,7222695916,prescott,6000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,az
1,7218891961,fayetteville,11900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ar
2,7221797935,florida keys,21000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,fl
3,7222270760,worcester / central MA,1500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ma
4,7210384030,greensboro,4900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nc
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
426875,7301591192,wyoming,23590,2019.0,nissan,maxima s sedan 4d,good,6 cylinders,gas,32226.0,clean,other,1N4AA6AV6KC367801,fwd,NaN,sedan,NaN,wy
426876,7301591187,wyoming,30590,2020.0,volvo,s60 t5 momentum sedan 4d,good,NaN,gas,12029.0,clean,other,7JR102FKXLG042696,fwd,NaN,sedan,red,wy
426877,7301591147,wyoming,34990,2020.0,cadillac,xt4 sport suv 4d,good,NaN,diesel,4174.0,clean,other,1GYFZFR46LF088296,NaN,NaN,hatchback,white,wy
426878,7301591140,wyoming,28990,2018.0,lexus,es 350 sedan 4d,good,6 cylinders,gas,30112.0,clean,other,58ABK1GG4JU103853,fwd,NaN,sedan,silver,wy
426879,7301591129,wyoming,30590,2019.0,bmw,4 series 430i gran coupe,good,NaN,gas,22716.0,clean,other,WBA4J1C58KBM14708,rwd,NaN,coupe,NaN,wy

In [5]:
#Look at unique values for different features
print(df['condition'].unique())
print(df['title_status'].unique())
print(df['transmission'].unique())
print(df['paint_color'].unique())
print(df['manufacturer'].unique())

[nan 'good' 'excellent' 'fair' 'like new' 'new' 'salvage']
[nan 'clean' 'rebuilt' 'lien' 'salvage' 'missing' 'parts only']
[nan 'other' 'automatic' 'manual']
[nan 'white' 'blue' 'red' 'black' 'silver' 'grey' 'brown' 'yellow'
 'orange' 'green' 'custom' 'purple']
[nan 'gmc' 'chevrolet' 'toyota' 'ford' 'jeep' 'nissan' 'ram' 'mazda'
 'cadillac' 'honda' 'dodge' 'lexus' 'jaguar' 'buick' 'chrysler' 'volvo'
 'audi' 'infiniti' 'lincoln' 'alfa-romeo' 'subaru' 'acura' 'hyundai'
 'mercedes-benz' 'bmw' 'mitsubishi' 'volkswagen' 'porsche' 'kia' 'rover'
 'ferrari' 'mini' 'pontiac' 'fiat' 'tesla' 'saturn' 'mercury'
 'harley-davidson' 'datsun' 'aston-martin' 'land rover' 'morgan']

In [6]:
'''Check for missing data for each feature'''
print("Percentage Missing for Different Features")
missing=df.isnull().sum()
percentage_missing=missing/len(df)
print(percentage_missing)
'''There are a lot of missing values for the size feature in particular'''
#Check for Value Counts for models 
print("------------------------------------")
print("Unique values for certain features")
print(df['model'].value_counts())
print(df['manufacturer'].value_counts())
'''Model type seems to have too many different kinds, manufacturer seems usable'''

Percentage Missing for Different Features
id              0.000000
region          0.000000
price           0.000000
year            0.002823
manufacturer    0.041337
model           0.012362
condition       0.407852
cylinders       0.416225
fuel            0.007058
odometer        0.010307
title_status    0.019308
transmission    0.005988
VIN             0.377254
drive           0.305863
size            0.717675
type            0.217527
paint_color     0.305011
state           0.000000
dtype: float64
------------------------------------
Unique values for certain features
model
f-150                      8009
silverado 1500             5140
1500                       4211
camry                      3135
silverado                  3023
                           ...
plymouth fury 1               1
f550 box truck delivery       1
duramax 2500hd                1
3 s sport                     1
Paige Glenbrook Touring       1
Name: count, Length: 29649, dtype: int64
manufacturer
ford               70985
chevrolet          55064
toyota             34202
honda              21269
nissan             19067
jeep               19014
ram                18342
gmc                16785
bmw                14699
dodge              13707
mercedes-benz      11817
hyundai            10338
subaru              9495
volkswagen          9345
kia                 8457
lexus               8200
audi                7573
cadillac            6953
chrysler            6031
acura               5978
buick               5501
mazda               5427
infiniti            4802
lincoln             4220
volvo               3374
mitsubishi          3292
mini                2376
pontiac             2288
rover               2113
jaguar              1946
porsche             1384
mercury             1184
saturn              1090
alfa-romeo           897
tesla                868
fiat                 792
harley-davidson      153
ferrari               95
datsun                63
aston-martin          24
land rover            21
morgan                 3
Name: count, dtype: int64

'Model type seems to have too many different kinds, manufacturer seems usable'

In [7]:
#look at number of vehicles that are in different price ranges
r0=len(df[df['price']==0])
r1=len(df[(df['price']<500) & (df['price']>=1)])
r2=len(df[(df['price']<5000) & (df['price']>=500)])
r3=len(df[(df['price']<10000) & (df['price']>=5000)])
r4=len(df[(df['price']<15000) & (df['price']>=10000)])
r5=len(df[(df['price']<20000) & (df['price']>=15000)])
r6=len(df[(df['price']>=20000) & (df['price']<25000)])
r7=len(df[(df['price']>=25000) & (df['price']<30000)])
r8=len(df[(df['price']>=30000) & (df['price']<35000)])
r9=len(df[(df['price']>=35000) & (df['price']<40000)])
r10=len(df[(df['price']>=40000) & (df['price']<45000)])
r11=len(df[(df['price']>=45000) & (df['price']<50000)])
r12=len(df[(df['price']>=50000) & (df['price']<55000)])
r13=len(df[df['price']>=55000])
print('$0:',r0,'\n$1 to $499:',r1,"\n$500 to $4999:",r2,"\n$5000 to $9999:",r3,"\n$10000 to $14999:",r4,"\n$15000 to $19999:",r5
      ,"\n$20000 to $24999:",r6,"\n$25000 to $29999:",r7,"\n$30000 to $34999:",r8,"\n$35000 to $39999:",r9,"\n$40000 to $44999:",r10,
     "\n$45000 to $49999:",r11,"\n$50000 to $54999:",r12,"\n>$55000:",r13)

$0: 32895
$1 to $499: 9199
$500 to $4999: 53218
$5000 to $9999: 79652
$10000 to $14999: 53811
$15000 to $19999: 49107
$20000 to $24999: 34812
$25000 to $29999: 34946
$30000 to $34999: 26552
$35000 to $39999: 23510
$40000 to $44999: 9494
$45000 to $49999: 6643
$50000 to $54999: 3773
>$55000: 9268

In [8]:
'''We should be able to remove all cars that cost $0 right off the bat.'''

'We should be able to remove all cars that cost $0 right off the bat.'

In [9]:
#Take a deeper look into the cars that are priced less than $500 to see if this makes any sense
df[(df['price']<500) & (df['price']>=1)]
#A lot of these seem to not make a lot of sense; there are examples of cars that are in good condition and have low mileage that are selling for <$500

,id,region,price,year,manufacturer,model,condition,cylinders,fuel,odometer,title_status,transmission,VIN,drive,size,type,paint_color,state
96,7309361405,auburn,80,2004.0,honda,NaN,excellent,6 cylinders,gas,94020.0,clean,automatic,NaN,NaN,NaN,NaN,NaN,al
369,7314941829,birmingham,199,2017.0,dodge,charger,NaN,NaN,gas,21737.0,clean,automatic,NaN,NaN,NaN,NaN,NaN,al
466,7314014511,birmingham,1,2012.0,ford,f250 super duty,NaN,NaN,gas,150000.0,clean,automatic,NaN,4wd,NaN,NaN,NaN,al
770,7311491693,birmingham,199,2017.0,dodge,charger,NaN,NaN,gas,21737.0,clean,automatic,NaN,NaN,NaN,NaN,NaN,al
951,7310466561,birmingham,199,2017.0,dodge,charger,NaN,NaN,gas,21737.0,clean,automatic,NaN,NaN,NaN,NaN,NaN,al
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
424919,7307410056,milwaukee,123,2013.0,chevrolet,suburban,like new,8 cylinders,gas,1234.0,clean,automatic,NaN,4wd,full-size,pickup,black,wi
424923,7307406918,milwaukee,123,2011.0,jeep,grand cherokee,like new,8 cylinders,gas,1234.0,clean,automatic,NaN,4wd,full-size,pickup,green,wi
425626,7316178541,wausau,1,2012.0,chevrolet,express,excellent,8 cylinders,gas,123.0,clean,automatic,NaN,4wd,full-size,van,NaN,wi
425627,7316168367,wausau,1,2012.0,chevrolet,express,excellent,8 cylinders,gas,1.0,clean,automatic,NaN,NaN,full-size,van,white,wi
425628,7316160520,wausau,1,2012.0,chevrolet,express,excellent,NaN,gas,123.0,clean,automatic,NaN,NaN,full-size,van,NaN,wi

### Data Preparation

After our initial exploration and fine-tuning of the business understanding, it is time to construct our final dataset prior to modeling.  Here, we want to make sure to handle any integrity issues and cleaning, the engineering of new features, any transformations that we believe should happen (scaling, logarithms, normalization, etc.), and general preparation for modeling with `sklearn`.

In [10]:
'''
Doing some research on the problem, it is clear that there are some columns that will not affect the price.
Specifically, this includes the identifier such as id and VIN. These should be dropped. It is also prudent to drop
certain non-numeric features that are missing a lot of values, such as type and paint_color, or have too many unique values,
such as model.
'''

'\nDoing some research on the problem, it is clear that there are some columns that will not affect the price.\nSpecifically, this includes the identifier such as id and VIN. These should be dropped. It is also prudent to drop\ncertain non-numeric features that are missing a lot of values, such as type and paint_color, or have too many unique values,\nsuch as model.\n'

In [11]:
df=pd.read_csv('data/vehicles.csv')
df.describe()

                 id         price           year      odometer
count  4.268800e+05  4.268800e+05  425675.000000  4.224800e+05
mean   7.311487e+09  7.519903e+04    2011.235191  9.804333e+04
std    4.473170e+06  1.218228e+07       9.452120  2.138815e+05
min    7.207408e+09  0.000000e+00    1900.000000  0.000000e+00
25%    7.308143e+09  5.900000e+03    2008.000000  3.770400e+04
50%    7.312621e+09  1.395000e+04    2013.000000  8.554800e+04
75%    7.315254e+09  2.648575e+04    2017.000000  1.335425e+05
max    7.317101e+09  3.736929e+09    2022.000000  1.000000e+07

In [12]:
#Remove any cars that are priced at less than $1000. Many of these prices do not seem to be realistic.
#Seems like some cars are basically being given away, and the price is not representative of their true properties
# Generally, the client will not be selling cars for less than $1000, so removing these outliers will allow us to get more accurate predictions for the
#rest of the data
df=pd.read_csv('data/vehicles.csv')
df=df[df['price']>=1000]

#Also going to remove cars that are over $300,000 to avoid extremely high-value vehicles skewing the model.
df=df[df['price']<300000]

#Remove columns for the VIN and ID as these do not have any bearing on the actual price
#Remove columns for paint_color and size as there are many rows missing this data
# Remove the 'models' column cause there are too many to accurately model
#Remove region as there is already a more general geographic identifier; geographic differences will be based on state if used
df_removed=df.drop(['VIN','id','model','region','paint_color','size','title_status'],axis=1)

#Remove any rows that are missing values for the:
#Condition, year, cylinders, and odometer because these are important determinants of price
df=df_removed
df=df.dropna(subset=['condition','year','odometer','cylinders','manufacturer'])
#Convert 'Cylinders' to Numerical Value, drop the rows with 'other' as the cylinder value
df['cylinders']=df['cylinders'].str.replace(" cylinders","")
df=df.query("cylinders!='other'")
df['cylinders']=pd.to_numeric(df['cylinders'])

#Convert the ordinal 'condition' data to a numerical scale
df['condition']=df['condition'].str.replace("salvage","0")
df['condition']=df['condition'].str.replace("fair","1")
df['condition']=df['condition'].str.replace("good","2")
df['condition']=df['condition'].str.replace("excellent","3")
df['condition']=df['condition'].str.replace("like new","4")
df['condition']=df['condition'].str.replace("new","5")
df['condition']=pd.to_numeric(df['condition'])

#Remove Tranmission types that are "other"
df=df.dropna(subset=['transmission'])
df=df.query("transmission!='other'")

#Remove types that are "other"
df=df.dropna(subset=['type'])
df=df.query("type != 'other'")

#Remove NaN for drive and remove 'other' values
df=df.dropna(subset=['drive'])
df=df.query("drive!='other'")

#Would like to convert the year value to an age value. Feel like the model will interpret this value more accurately.
df['year']=2026-df['year']
df=df.rename(columns={'year':'age'})

#Scale the numeric values
numeric=['age','cylinders','odometer','condition']
categorical=['manufacturer','fuel','transmission','drive','type','state']
print(df.isnull().sum())

C:\Users\matth\AppData\Local\Temp\ipykernel_41912\1561306023.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['cylinders']=df['cylinders'].str.replace(" cylinders","")

price           0
age             0
manufacturer    0
condition       0
cylinders       0
fuel            0
odometer        0
transmission    0
drive           0
type            0
state           0
dtype: int64

In [13]:
#These are the base features we will use for crafting the model
df

,price,age,manufacturer,condition,cylinders,fuel,odometer,transmission,drive,type,state
31,15000,13.0,ford,3,6,gas,128000.0,automatic,rwd,truck,al
34,35000,7.0,toyota,3,6,gas,43000.0,automatic,4wd,truck,al
55,19900,22.0,ford,2,8,diesel,88000.0,automatic,4wd,pickup,al
59,14000,14.0,honda,3,6,gas,95000.0,automatic,fwd,mini-van,al
65,22500,25.0,ford,2,8,diesel,144700.0,manual,rwd,truck,al
...,...,...,...,...,...,...,...,...,...,...,...
426820,32990,15.0,mercedes-benz,2,8,gas,82763.0,automatic,rwd,sedan,wy
426823,37590,8.0,mercedes-benz,2,6,gas,16482.0,automatic,rwd,SUV,wy
426831,9800,41.0,nissan,4,6,gas,115000.0,automatic,rwd,hatchback,wy
426833,6800,29.0,jaguar,2,8,gas,69550.0,automatic,rwd,convertible,wy
426874,33590,8.0,lexus,2,6,gas,30814.0,automatic,rwd,sedan,wy

In [14]:
#One-Hot Encode the categorical features

#State
state_dummies=pd.get_dummies(df['state'],dtype='int')
df=pd.concat([df,state_dummies],axis=1)
df=df.drop("state",axis=1)

#Manufacturer
manufacturer_dummies=pd.get_dummies(df['manufacturer'],dtype='int')
df=pd.concat([df,manufacturer_dummies],axis=1)
df=df.drop("manufacturer",axis=1)

#Transmission
transmission_dummies=pd.get_dummies(df['transmission'],dtype='int')
df=pd.concat([df,transmission_dummies],axis=1)
df=df.drop("transmission",axis=1)

#Fuel
fuel_dummies=pd.get_dummies(df['fuel'],dtype='int')
df=pd.concat([df,fuel_dummies],axis=1)
df=df.drop("fuel",axis=1)

#Type
type_dummies=pd.get_dummies(df['type'],dtype='int')
df=pd.concat([df,type_dummies],axis=1)
df=df.drop("type",axis=1)

#Drive
drive_dummies=pd.get_dummies(df['drive'],dtype='int')
df=pd.concat([df,drive_dummies],axis=1)
df=df.drop("drive",axis=1)

In [15]:
#ALso noticed that some odometer readings are extremely high, want to cutoff the milage permitted for cars to not skew the data.
df=df[df['odometer']<300000]

In [16]:
df

,price,age,condition,cylinders,odometer,ak,al,ar,az,ca,...,mini-van,offroad,pickup,sedan,truck,van,wagon,4wd,fwd,rwd
31,15000,13.0,3,6,128000.0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,0,1
34,35000,7.0,3,6,43000.0,0,1,0,0,0,...,0,0,0,0,1,0,0,1,0,0
55,19900,22.0,2,8,88000.0,0,1,0,0,0,...,0,0,1,0,0,0,0,1,0,0
59,14000,14.0,3,6,95000.0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
65,22500,25.0,2,8,144700.0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
426820,32990,15.0,2,8,82763.0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
426823,37590,8.0,2,6,16482.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
426831,9800,41.0,4,6,115000.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
426833,6800,29.0,2,8,69550.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
426874,33590,8.0,2,6,30814.0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1

In [17]:
# Create training and test sets
x = df.drop('price', axis=1)
y = df['price']
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

# A category for the manufacturer occurs ONLY in the test set.
variable_cols = x_train.columns[x_train.nunique(dropna=False) > 1]
removed_cols = x_train.columns.difference(variable_cols)
x_train = x_train[variable_cols].copy()
x_test = x_test[variable_cols].copy()

In [18]:
#Perform Scaling on numeric features
scaler=StandardScaler()
numeric=['age','cylinders','odometer','condition']
x_train_scaled=x_train.copy()
x_test_scaled=x_test.copy()
x_train_scaled[numeric]=scaler.fit_transform(x_train_scaled[numeric])
x_test_scaled[numeric]=scaler.transform(x_test_scaled[numeric])

### Modeling

With your (almost?) final dataset in hand, it is now time to build some models.  Here, you should build a number of different regression models with the price as the target.  In building your models, you should explore different parameters and be sure to cross-validate your findings.

In [19]:
#Model 1: Simple Linear Regression

#Make and fit linear regression model
m1=linear_model.LinearRegression(fit_intercept=True)
m1.fit(x_train,y_train)
#Get predictions of Model 1
m1_preds=m1.predict(x_test)
#Evaluate Model, choosing to use RMSE so that we still get our analysis in terms of dollars of error for ease of analysis but keep the benefits of MSE
RMSE_m1=np.sqrt(mean_squared_error(y_test,m1_preds))
print("Linear Model RMSE: "+ str(RMSE_m1))
#End up with an RMSE of around $8.1k. This is not completely terrible but definitely not ideal.

Linear Model RMSE: 8161.8100237571025

In [33]:
# Model 2: Polynomial features with ordinary Linear Regression
from sklearn.preprocessing import PolynomialFeatures, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

numeric = ['age', 'condition', 'cylinders','odometer']

numeric_transformer = Pipeline([
    ('scaler', StandardScaler()),
    ('poly', PolynomialFeatures(degree=2, include_bias=False)),
    ('poly_scaler', StandardScaler())
])
preprocessor = ColumnTransformer([
    ('numeric_poly', numeric_transformer, numeric)
], remainder='passthrough')

m2 = Pipeline([
    ('preprocessor', preprocessor),
    ('regression', LinearRegression())
])
m2.fit(x_train, y_train)
m2_preds = m2.predict(x_test)
RMSE_m2 = np.sqrt(mean_squared_error(y_test, m2_preds))

print('Polynomial Regression RMSE: '+str(RMSE_m2))

Polynomial Regression RMSE: 6946.571716004741

RMSE: $7,129.17

In [21]:
#Running a polynomial regression results in an RMSE of around $6.9k, which is notably better than the linear model

In [25]:
# Model 3: Ridge Regression with Sequential Feature Selection

from sklearn.linear_model import Ridge, RidgeCV
from sklearn.feature_selection import (
    SelectKBest, f_regression, SequentialFeatureSelector
)
from sklearn.metrics import mean_squared_error
import numpy as np

sample_idx = x_train_scaled.sample(
    n=min(3000, len(x_train_scaled)),
    random_state=42
).index

X_sample = x_train_scaled.loc[sample_idx]
y_sample = y_train.loc[sample_idx]

#Identify 15 features
initial_selector = SelectKBest(
    score_func=f_regression,
    k=15
)

initial_selector.fit(X_sample, y_sample)

top_features = X_sample.columns[
    initial_selector.get_support()
].tolist()

#Run SFS on the 15 features
sfs = SequentialFeatureSelector(
    Ridge(alpha=100, solver='lsqr'),
    n_features_to_select=6,
    direction='forward',
    scoring='neg_root_mean_squared_error',
    cv=2,
    n_jobs=1
)

sfs.fit(X_sample[top_features], y_sample)

#Get selected features
selected_features = [
    f for f, selected in zip(
        top_features, sfs.get_support()
    ) if selected
]

print("Selected Features:")
print(selected_features)

#Fit Ridge on the full training dataset
m3 = RidgeCV(
    alphas=[0.1, 1, 10, 100, 1000],
    cv=3,
    scoring='neg_root_mean_squared_error'
)

m3.fit(
    x_train_scaled[selected_features],
    y_train
)

# Step 6: Evaluate on testing data
m3_preds = m3.predict(
    x_test_scaled[selected_features]
)

RMSE_m3 = np.sqrt(mean_squared_error(y_test, m3_preds))

print("Ridge RMSE: "+str(RMSE_m3))

Selected Features:
['age', 'cylinders', 'odometer', 'diesel', 'gas', 'fwd']
Ridge RMSE: 8679.743888817522

In [32]:
# Model 4: Lasso Regression

from sklearn.linear_model import LassoCV

m4 = LassoCV(
    alphas=[1, 10, 50, 100, 250, 500, 1000],
    cv=3,
    max_iter=10000,
    n_jobs=-1,
    random_state=42
)

m4.fit(x_train_scaled, y_train)

m4_preds = m4.predict(x_test_scaled)

RMSE_m4 = np.sqrt(mean_squared_error(y_test, m4_preds))

print("Lasso RMSE: "+str(RMSE_m4))

Lasso RMSE: 8155.449200086182

### Evaluation

With some modeling accomplished, we aim to reflect on what we identify as a high-quality model and what we are able to learn from this.  We should review our business objective and explore how well we can provide meaningful insight into drivers of used car prices.  Your goal now is to distill your findings and determine whether the earlier phases need revisitation and adjustment or if you have information of value to bring back to your client.

In [ ]:
'''
Through modeling, we compared a linear regression model, a polynomial regression model, and a ridge regression model. From our data, we can see that 
the polynomial regression model performed the best, with an RMSE of around $6.9k. This tells us that relationships between the vehicle characteristics and price
are probably non-linear.'''

In [ ]:
'''Some improvements definetly could've been made. Especially in the data cleaning stage. I was able to catch outliers for odometer values which
ruined some of my initial testing of the models but some other outliers in other features could've skewed the models. I also could've found different
ways to deal with missing data rather than just removing it. Additionally, I could've utilized LASSO and Ridge regression in combination of Polynomial 
regression to get a more accurate model'''

### Deployment

Now that we've settled on our models and findings, it is time to deliver the information to the client.  You should organize your work as a basic report that details your primary findings.  Keep in mind that your audience is a group of used car dealers interested in fine-tuning their inventory.

In [ ]:
'''
Through analysis of 4 different models, we have come to the conclusion that a polynomial regression model is the most accurate at predicting car
prices. With our test data, we were able to reduce the model error to about $7k from the actual car price. This model took into
account the condition, fuel type, age, condition, cylinder number, mileage, state, manufacturer, transmission, drive, and car type. Using these features
along with our model, you should be able to get a broad estimate of car pricing given the car's characteristics and your geographic location. Additionally,
the model should help you identify any inconsistencies in pricing in your current inventory.
'''